# - name: Add wireshark stable repository from PPA and install its signing key on Debian target
#   ansible.builtin.apt_repository:
#     repo: 'ppa:wireshark-dev/stable'

- name: Update the repository cache and install some debugging tools
  apt:
    update_cache: yes
    pkg:
    - bat
    - curl
    # - exa
    - htop
    - net-tools
    - python3-dev
    - python3-venv
    - unzip
    - vim
    - wget

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /home/{{ account }}/.local/bin/bat
    owner: "{{ account }}"
    group: "{{ account }}"
    state: link
