# - name: Add wireshark stable repository from PPA and install its signing key on Debian target
#   ansible.builtin.apt_repository:
#     repo: 'ppa:wireshark-dev/stable'

- name: Update the repository cache and install some debugging tools
  apt:
    update_cache: yes
    pkg:
    - bat
    - curl
    - wget
    # - exa
    - htop
    - net-tools
    - unzip
    - vim
    - jq
    - python3.9
    - python3.9-dev
    - python3.9-venv

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "/home/{{ account }}/bin/bat"
    owner: "{{ account }}"
    group: "{{ account }}"
    state: link
