- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Make sure we have a 'docker' group
  group:
    name: docker
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers users to wheel group
  user:
    name: alex
    groups:
      - wheel
      - docker
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: "Create /home/{{ account }}/.local/bin"
  file:
    path: "/home/{{ account }}/.local/bin"
    state: directory
    owner: "{{ account }}"
    group: "{{ account }}"
    mode: '0755'

- name: "Create /home/{{ account }}/bin"
  file:
    path: "/home/{{ account }}/bin"
    state: directory
    owner: "{{ account }}"
    group: "{{ account }}"
    mode: '0755'

- name: copy over .bash_aliases
  copy:
    src: .bash_aliases
    dest: "/home/{{ account }}/.bash_aliases"
    owner: "{{ account }}"
    group: "{{ account }}"
    mode: '0644'