---
- name: Update from git
  git:
    repo: "https://github.com/ryanoasis/nerd-fonts.git"
    dest: "{{ ansible_env.HOME }}/src/ikon/nerd-fonts"
    depth: 1
    force: yes

- name: Select fonts to install
  find:
    recurse: yes
    use_regex: yes
    paths: "{{ ansible_env.HOME }}/src/ikon/nerd-fonts/patched-fonts"
    patterns:
      - '^.*?((?!Windows).)*?\.ttf$'
  register: fonts_to_install

#- debug: var=fonts_to_install

- copy:
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item.path | basename }}"
    src: "{{ item.path }}"
    remote_src: yes
  loop: "{{ fonts_to_install.files }}"

- name: 'rebuild fonts cache'
  shell: 'fc-cache -v -f'