---
- name: Update from git
  git:
    repo: "https://github.com/ryanoasis/nerd-fonts.git"
    dest: "/tmp/nerd-fonts"
    depth: 1
    force: yes

- name: Select fonts to install
  find:
    recurse: yes
    use_regex: yes
    paths: "/tmp/nerd-fonts/patched-fonts"
    patterns:
      - '^.*?((?!Windows).)*?\.ttf$'
  register: fonts_to_install

#- debug: var=fonts_to_install
- name: "Create /home/{{ account }}/.local/share/fonts"
  file:
    path: "/home/{{ account }}/.local/share/fonts"
    state: directory
    owner: "{{ account }}"
    group: "{{ account }}"
    mode: '0755'

- copy:
    dest: "/home/{{account}}/.local/share/fonts/{{ item.path | basename }}"
    src: "{{ item.path }}"
    remote_src: yes
  loop: "{{ fonts_to_install.files }}"

- name: 'rebuild fonts cache'
  shell: 'fc-cache -v -f'